version: '3.7'

services:

  web:
    container_name: web
    build: ./
    volumes:
      - './web:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
